# -*- coding: utf-8 -*-
"""GSiot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q7hYnTvuAb_CIgNSPJl8iO0Sx9FCsziw
"""

!pip install -q -U google-generativeai

import google.generativeai as genai
import time
import random
import json
import requests
from datetime import datetime
import logging

# --- 1. CONFIGURAÇÕES ---
GOOGLE_API_KEY = "AIzaSyCu2ZXRHQBRqsQbqbx8gAKpv2ZlZ7P6P10" # Sua chave
genai.configure(api_key=GOOGLE_API_KEY)

# Desativar logs de erro do sistema
logger = logging.getLogger()
logger.setLevel(logging.CRITICAL)

# !!! COLE SEU LINK DO NGROK AQUI !!!
# Exemplo: "https://a1b2-c3d4.ngrok-free.app"
URL_API = "https://deneen-mugwumpish-excursively.ngrok-free.dev"

# --- 2. FUNÇÕES ---
def gerar_dados_iob(id_colaborador):
    stress = random.randint(10, 95)
    foco = max(5, 100 - int(stress * 0.9) + random.randint(-10, 10))
    bpm = 60 + (stress // 2) + random.randint(-5, 15)
    return { "colaborador_id": id_colaborador, "nivel_stress": stress, "nivel_foco": foco, "batimentos": bpm }

def analisar_desafio(titulo):
    print(f"   🧠 IA Analisando: '{titulo}'...")
    time.sleep(1)
    try:
        model = genai.GenerativeModel('models/gemini-2.0-flash')
        prompt = f"Resuma solução para: '{titulo}'. Responda JSON: {{ 'sugestao': '...', 'perfil_profissional': '...' }}"
        response = model.generate_content(prompt)
        # Limpeza extra para garantir JSON válido
        texto = response.text.replace("```json", "").replace("```", "").strip()
        return json.loads(texto)
    except:
        return {"sugestao": "Aplicar metodologia ágil.", "perfil_profissional": "Squad Leader"}

# --- 3. SETUP AUTOMÁTICO (Cria o Desafio 1 para evitar erro 404) ---
if URL_API:
    print("--- 🛠️ SETUP: Verificando API Java ---")
    try:
        setup_json = {"titulo": "Inclusão Tech", "descricao": "Setup Inicial"}
        # Tenta criar o desafio ID 1
        requests.post(f"{URL_API}/api/desafios", json=setup_json)
        print("   ✅ Setup concluído! Banco de dados preparado.")
    except Exception as e:
        print(f"   ⚠️ Aviso: Não foi possível conectar na API ({e})")

# --- 4. LOOP PRINCIPAL ---
print("\n--- 🚀 INICIANDO AGENTE SYNAPSE ---")
desafios = ["Inclusão Tech", "Burnout Zero", "Energia Verde"]

try:
    while True:
        print("--- 📡 CICLO DE MONITORAMENTO ---")
        # IoB
        for id in [101, 102, 103]:
            dados = gerar_dados_iob(id)
            print(f"[IoB] Colab {id} | Stress: {dados['nivel_stress']}% | Foco: {dados['nivel_foco']}%")
            if URL_API:
                try: requests.post(f"{URL_API}/api/iob/biometria", json=dados)
                except: pass

        # IA
        if random.random() < 0.4:
            titulo = random.choice(desafios)
            analise = analisar_desafio(titulo)
            print(f"📝 IA SUGERIU: {analise.get('sugestao')}")
            if URL_API:
                try:
                    payload = {"sugestao": analise.get('sugestao'), "perfilProfissional": analise.get('perfil_profissional')}
                    requests.post(f"{URL_API}/api/desafios/1/analise", json=payload)
                    print("   ✅ Enviado para Java")
                except: pass

        print("")
        time.sleep(5)
except KeyboardInterrupt:
    print("Parado.")